platform :ios, '8.0'
#use_frameworks!
inhibit_all_warnings!

post_install do |installer|
    
    puts 'Determining pod project minimal deployment target'
    
    pods_project = installer.pods_project
    deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
    deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
    minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
    
    puts 'Minimal deployment target is ' + minimal_deployment_target
    puts 'Setting each pod deployment target to ' + minimal_deployment_target
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings[deployment_target_key] = minimal_deployment_target
        end
    end
end

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'
inhibit_all_warnings! #inhibit_warnings参数能够有效的抑制CocoaPods引入的第三方代码库产生的warning。

target 'CJMonitorDemo' do
    pod 'CJBaseUIKit',  :subspecs => ['UIColor', 'UIButton', 'UITextField']
    pod 'CJFoundation', :subspecs => ['NSString']
    pod 'CJBaseHelper', :subspecs => ['NSObjectCJHelper', 'UIViewControllerCJHelper', 'AuthorizationCJHelper']
    pod 'CJBaseUtil',   :subspecs => ['CJDataUtil']
    pod 'CQDemoKit',    '~> 0.3.1',      :subspecs => ['Home_Base']
    
    pod 'IQKeyboardManager'
    pod 'DZNEmptyDataSet'
    
    pod 'CJMonitor',        :path => '~/Project/Github/CJMonitor’
end

target 'CJMonitorDemoTests' do
    platform :ios, '9.0'
    #pod 'OCMock', '~> 3.4.1'
    pod 'CJBaseTest/Test'
end

target 'CJMonitorDemoUITests' do
    platform :ios, '9.0'
    pod 'CJBaseTest/UITest'
end
